package com.lom.futures.enums.bot;

public enum Action {

    OPEN,
    CLOSE,
    WAIT,
    NOTHING,
    OPEN_LONG,
    OPEN_SHORT,
    OPEN_LONG_CLOSE_SHORT,
    OPEN_SHORT_CLOSE_LONG,
    OPEN_LONG_CLOSE_SHORT_TP,
    OPEN_SHORT_CLOSE_LONG_TP,
    OPEN_LONG_CLOSE_SHORT_SL,
    OPEN_SHORT_CLOSE_LONG_SL,
    CLOSE_LONG,
    CLOSE_LONG_TP,
    CLOSE_LONG_SL,
    CLOSE_SHORT_TP,
    CLOSE_SHORT_SL,
    CLOSE_SHORT


}
